Expanded test suite

diff --git a/test/t_factors b/test/t_factors
--- a/test/t_factors
+++ b/test/t_factors
@@ -5,26 +5,34 @@
 # or the GNU Library General Public License (LGPL) version 2 or later
 # <http://www.gnu.org/copyleft/lgpl.html>
 #
-# $Id: t_factors,v 1.3 2004/01/12 10:32:59 lha Exp $
+# $Id: t_factors,v 1.4 2004/01/17 05:31:56 lha Exp $
 #
 
-try() {
+# try_order comment query pattern1 patern2 ...
+#	comment	- description of test, displayed if error occurs
+#	query	- search string passed to  htsearch
+#	pattern	- strings expected to occur *in order* in the output
+try_order() {
     comment="$1"
     shift
     query="$1"
     shift
     $htsearch -c $config "$query" > $tmp 2> /dev/null
+    array=""
     for pattern
     do
-	if grep "$pattern" $tmp > /dev/null 
-	then :
-	else
-	    $htsearch -vv -c $config "$query" > /dev/null
-	    echo "Output doesn't match \"$pattern\""
-	    fail "$htsearch -c $config '$query' >> $tmp --
-		  $comment"
-	fi
+	array="$array; array[i++] = "\"$pattern\"
     done
+    miss=`$awk "BEGIN {$array; line = 0; } \
+	    "'$0'" ~ array[line] { line++ } \
+	    END { print array[line] } " < $tmp `
+    if [ "$miss" != "" ]
+    then
+	$htsearch -vv -c $config "$query" > /dev/null
+	echo "String \"$miss\" was not found where expected"
+	fail "$htsearch -c $config '$query' >> $tmp --
+	      $comment"
+    fi
 }
 
 
@@ -39,6 +47,39 @@ tmp=/tmp/t_htsearch$$
 # set up config file with chosen non-default values
 cp $testdir/conf/htdig.conf $config
 
+$htdig "$@" -t -i -c $config	|| fail "Couldn't dig"
+$htpurge -c $config		|| fail "Couldn't purge"
+
+try_order "Search for 'also'" \
+    "words=also" \
+    '4 matches' 'site2.html' 'site4.html' 'bad_local.htm' 'script.html'
+
+set_attr url_seed_score		"site4 *1000+1000"
+try_order "Seed score 1000 for site4.html" \
+    "words=also" \
+    '4 matches' 'site4.html' 'site2.html' 'bad_local.htm' 'script.html'
+
+set_attr url_seed_score		"site4 *1000+1000 script *1000+1000"
+try_order "Seed score 1000 for site4.html and script.html" \
+    "words=also" \
+    '4 matches' 'site4.html' 'script.html' 'site2.html' 'bad_local.htm'
+
+set_attr url_seed_score		"site4|script *1000+1000"
+try_order "Seed score 1000 for site4|script" \
+    "words=also" \
+    '4 matches' 'site4.html' 'script.html' 'site2.html' 'bad_local.htm'
+
+set_attr search_results_order		"bad_local"
+try_order "Search_results_order bad_local" \
+    "words=also" \
+    '4 matches' 'bad_local.htm' 'site4.html' 'script.html' 'site2.html'
+
+set_attr search_results_order		"script * e2|e4"
+try_order "Search_results_order * script e2|e4" \
+    "words=also" \
+    '4 matches' 'script.html' 'bad_local.htm' 'site4.html' 'site2.html'
+
+set_attr url_seed_score		""
 set_attr author_factor			0
 set_attr backlink_factor		0
 set_attr caps_factor			0
@@ -52,29 +93,15 @@ set_attr text_factor			0
 set_attr title_factor			0
 set_attr url_text_factor		0
 
-set_attr heading_factor_1		1
-($htdig "$@" -t -i -c $config	|
-    grep "option heading_factor_1 is no longer supported" > /dev/null ) ||
-    fail "Couldn't dig"
-
-$htpurge -c $config		|| fail "Couldn't purge"
-
-################################################################################
-## Add tests here
-################################################################################
-
-cp $testdir/conf/htdig.conf $config
-
-try "Search for also" \
-    "words=also" \
-    'Movies</a></strong><img src="/htdig/star.gif" alt="\*"><img src="/htdig/star.gif" alt="\*"><img src="/htdig/star.gif" alt="\*"><img src="/htdig/star.gif" alt="\*">'
-    'Node</a></strong><img src="/htdig/star.gif" alt="*"><img src="/htdig/star_blank'
-
-set_attr url_seed_score		"script|bad_local *1000+1000"
-
-try "Biassed earch for also" \
+try_order "Search with factors 0" \
     "words=also" \
     'No matches'
+
+set_attr description_factor		1
+
+try_order "Search for 'crossRef' with description_factor 1" \
+    "words=crossRef" \
+    '1 matches' 'site%201.html'
 
 test_functions_action=--stop-apache
 . ./test_functions
diff --git a/test/t_htdig_local b/test/t_htdig_local
--- a/test/t_htdig_local
+++ b/test/t_htdig_local
@@ -5,26 +5,56 @@
 # or the GNU Library General Public License (LGPL) version 2 or later
 # <http://www.gnu.org/copyleft/lgpl.html>
 #
-# $Id: t_htdig_local,v 1.7 2003/09/27 06:53:29 lha Exp $
+# $Id: t_htdig_local,v 1.8 2004/01/17 05:31:56 lha Exp $
 #
+
+# Tests the following config attributes:
+#	bad_local_extensions
+#	content_classifier
+#	database_dir
+#	exclude_urls
+#	local_extensions
+#	mime_types
+#	start_url
 
 test_functions_action=--start-apache
 . ./test_functions
 
+# set up config file with chosen non-default values
+config=$testdir/conf/htdig.conf.tmp
+cp $testdir/conf/htdig.conf2 $config
+
 #test for local-file-system access to <http://...> URLs
 
+/bin/rm -f var/htdig2/*
 expected='bad_local.htm'
-got=`$htdig "$@" -t -i -vv -c $testdir/conf/htdig.conf2 | grep "Bad local extension:" | sed -e"s-.*/--"`
+got=`$htdig "$@" -t -i -vv -c $config | grep "Bad local extension:" | sed -e"s-.*/--"`
 if [ "$expected" != "$got" ]
 then
-	fail "running htdig: expected 
+	fail "first htdig: expected 
 $expected
 but got
 $got"
 
 fi
 
-$htpurge -c $testdir/conf/htdig.conf2
+expected='db.docdb
+db.docs
+db.docs.index
+db.excerpts
+db.worddump
+db.words.db
+db.words.db_weakcmpr'
+got=`/bin/ls var/htdig2`
+if [ "$expected" != "$got" ]
+then
+	fail "created files: expected 
+$expected
+but got
+$got"
+fi
+
+$htpurge -c $config
 
 # should  http://localhost:7400/set1/sub%2520dir  be purged?
 expected='http://localhost:7400/set1/
@@ -38,11 +68,11 @@ http://localhost:7400/set1/sub%2520dir/
 http://localhost:7400/set1/sub%2520dir/empty%20file.html
 http://localhost:7400/set1/title.html'
 
-got=`./document -c $testdir/conf/htdig.conf2 -u | sort`
+got=`./document -c $config -u | sort`
 
 if [ "$expected" != "$got" ]
 then
-	fail "running htdig: expected 
+	fail "first document: expected 
 $expected
 but got
 $got"
@@ -53,18 +83,19 @@ fi
 #test for  <file:///...> URLs
 
 expected=''	# no "bad local" extensions for file:///
-sed "s#^start_url.*#start_url: file://$PWD/htdocs/set1/#" < $testdir/conf/htdig.conf2 > tmp.conf
-got=`$htdig "$@" -t -i -vv -c tmp.conf | grep "Bad local extension:" | sed -e"s-.*/--"`
+#sed "s#^start_url.*#start_url: file://$PWD/htdocs/set1/#" < $config > tmp.conf
+set_attr start_url file://$PWD/htdocs/set1/
+got=`$htdig "$@" -t -i -vv -c $config | grep "Bad local extension:" | sed -e"s-.*/--"`
 if [ "$expected" != "$got" ]
 then
-	fail "running htdig: expected 
+	fail "second htdig: expected 
 $expected
 but got
 $got"
 
 fi
 
-$htpurge -c $testdir/conf/htdig.conf2
+$htpurge -c $config || fail "couldn't purge second time"
 
 expected='file:///set1/bad_local.htm
 file:///set1/index.html
@@ -76,16 +107,62 @@ file:///set1/site4.html
 file:///set1/sub%2520dir/empty%20file.html
 file:///set1/title.html'
 
-got=`./document -c tmp.conf -u | sed "s#${PWD}/htdocs##" | sort`
+got=`./document -c $config -u | sed "s#${PWD}/htdocs##" | sort`
 
 if [ "$expected" != "$got" ]
 then
-	fail "running htdig: expected 
+	fail "second document: expected 
 $expected
 but got
 $got"
 
 fi
+
+
+#test mime types handling
+
+expected=''	# no "bad local" extensions for file:///
+set_attr mime_types $PWD/mime-without-htm
+set_attr content_classifier $PWD/say-text
+echo 'text/html	html' > mime-without-htm
+echo '#!/bin/sh
+      echo text/plain' > say-text
+chmod 700 say-text
+got=`$htdig "$@" -t -i -vv -c $config | grep "MIME type:" | sed -e"s-.*/--"`
+if [ "$expected" != "$got" ]
+then
+	fail "third htdig: expected 
+$expected
+but got
+$got"
+
+fi
+
+$htpurge -c $config || fail "couldn't purge second time"
+
+expected='file:///set1/bad_local.htm
+file:///set1/index.html
+file:///set1/nph-location.foo
+file:///set1/script.html
+file:///set1/site%201.html
+file:///set1/site2.html
+file:///set1/site3.html
+file:///set1/site4.html
+file:///set1/sub%2520dir/empty%20file.html
+file:///set1/title.html'
+
+got=`./document -c $config -u | sed "s#${PWD}/htdocs##" | sort`
+
+if [ "$expected" != "$got" ]
+then
+	fail "third document: expected 
+$expected
+but got
+$got"
+
+fi
+
+/bin/rm mime-without-htm say-text
 
 test_functions_action=--stop-apache
 . ./test_functions
diff --git a/test/t_parsing b/test/t_parsing
--- a/test/t_parsing
+++ b/test/t_parsing
@@ -5,25 +5,21 @@
 # or the GNU Library General Public License (LGPL) version 2 or later
 # <http://www.gnu.org/copyleft/lgpl.html>
 #
-# $Id: t_parsing,v 1.1 2004/01/12 10:32:59 lha Exp $
+# $Id: t_parsing,v 1.2 2004/01/17 05:31:56 lha Exp $
 #
 
 
 # Tests (or should eventually test) the following config attributes:
 #	description_meta_tag_names
-#	date_format
 #	ignore_alt_text
 #	max_doc_size
 #	max_keywords
 #	max_meta_description_length
 #	max_description_length
 #	max_descriptions
-#	max_excerpts
 #	max_head_length
 #	noindex_end
 #	noindex_start
-#	mime_types
-#	content_classifier
 #	external_parsers
 #	external_protocols
 #	use_meta_description
@@ -60,21 +56,17 @@ try() {
 
 # Tests (or should eventually test) the following config attributes:
 #	description_meta_tag_names
-#	date_format			(Should be in t_htsearch/t_templates)
 #	ignore_alt_text
 #	max_doc_size
 #	max_keywords
 #	max_meta_description_length
-#	max_description_length		(May put in t_factors)
-#	max_descriptions		(May put in t_factors)
-#	max_excerpts			(Should be in t_htsearch/t_templates)
+#	max_description_length		(May put in t_templates)
+#	max_descriptions		(May put in t_templates)
 #	max_head_length
 #	noindex_end
 #	noindex_start
-#	mime_types			(TODO)
-#	content_classifier		(TODO)
 #	external_parsers		(TODO)
-#	external_protocols		(TODO)
+#	external_protocols
 #	use_meta_description
 
 $htdig "$@" -t -i -c $config	|| fail "Couldn't do first dig"
@@ -174,9 +166,25 @@ try "Search for 'technical', noindex_start=software distribution, noindex_end=co
     "words=technical" \
     'No matches'
 
+PROTOCOL=my-protocol
+echo '#!/bin/sh
+      echo "s	200"
+      echo "t	text/html"
+      echo
+      echo "<html>$2</html>"' > $PROTOCOL
+chmod 755 $PROTOCOL
+set_attr external_protocols "echo: $PWD/$PROTOCOL"
+set_attr start_url "echo:foo.html"
+$htdig "$@" -t -i -c $config -vvv | less
+$htdig "$@" -t -i -c $config	|| fail "Couldn't do fourth dig"
+try "trying external protocol  echo" \
+    "words=foo" \
+    "1 matches" "echo:foo.html"
+
+
 test_functions_action=--stop-apache
 . ./test_functions
 
-rm -f $tmp
+rm -f $tmp $PROTOCOL
 
 exit 0
