Add test for FD_SET_T, the second (also third and fourth) argument in calls to select(). Should solve PR#739.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4092,6 +4092,49 @@ EOF
 
 fi
 
+echo $ac_n "checking how to call select?""... $ac_c" 1>&6
+echo "configure:4097: checking how to call select?" >&5
+for fd_set_t in 'fd_set' 'int'
+  do
+    cat > conftest.$ac_ext <<EOF
+#line 4101 "configure"
+#include "confdefs.h"
+#include <sys/time.h>
+#include <sys/types.h>
+#include <unistd.h>
+ extern "C" int select(int, $fd_set_t *, $fd_set_t *, $fd_set_t *, struct timeval *);
+ $fd_set_t fd; 
+int main() {
+ select(0, &fd, 0, 0, 0); 
+; return 0; }
+EOF
+if { (eval echo configure:4112: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+  rm -rf conftest*
+  ac_found=yes ; break 2
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  ac_found=no
+fi
+rm -f conftest*
+done
+
+if test "$ac_found" = no
+then
+  echo "configure: warning: can't determine argument type using int" 1>&2
+  cat >> confdefs.h <<EOF
+#define FD_SET_T int
+EOF
+
+else
+  echo "$ac_t""$fd_set_t" 1>&6
+  cat >> confdefs.h <<EOF
+#define FD_SET_T $fd_set_t
+EOF
+
+fi
+
 ac_ext=C
 # CXXFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
 ac_cpp='$CXXCPP $CPPFLAGS'
@@ -4100,16 +4143,16 @@ ac_link='${CXX-g++} -o conftest${ac_exeext} $CXXFLAGS $CPPFLAGS $LDFLAGS conftes
 cross_compiling=$ac_cv_prog_cxx_cross
 
 echo $ac_n "checking for bool data type?""... $ac_c" 1>&6
-echo "configure:4104: checking for bool data type?" >&5
+echo "configure:4147: checking for bool data type?" >&5
 cat > conftest.$ac_ext <<EOF
-#line 4106 "configure"
+#line 4149 "configure"
 #include "confdefs.h"
 
 int main() {
 bool i;
 ; return 0; }
 EOF
-if { (eval echo configure:4113: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:4156: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   echo "$ac_t""yes" 1>&6;cat >> confdefs.h <<\EOF
 #define HAVE_BOOL 1
@@ -4124,16 +4167,16 @@ fi
 rm -f conftest*
 
 echo $ac_n "checking for true and false?""... $ac_c" 1>&6
-echo "configure:4128: checking for true and false?" >&5
+echo "configure:4171: checking for true and false?" >&5
 cat > conftest.$ac_ext <<EOF
-#line 4130 "configure"
+#line 4173 "configure"
 #include "confdefs.h"
 
 int main() {
 int i, j; i= true; j= false;
 ; return 0; }
 EOF
-if { (eval echo configure:4137: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:4180: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   echo "$ac_t""yes" 1>&6
      cat >> confdefs.h <<\EOF
@@ -4166,7 +4209,7 @@ fi
 if $htdig_cv_tests
 then
 	echo $ac_n "checking user name""... $ac_c" 1>&6
-echo "configure:4170: checking user name" >&5
+echo "configure:4213: checking user name" >&5
 test -n "$LOGNAME" && USER=$LOGNAME
 
 echo "$ac_t""$USER" 1>&6
@@ -4176,7 +4219,7 @@ echo "$ac_t""$USER" 1>&6
 #
 
  echo $ac_n "checking if apache is wanted""... $ac_c" 1>&6
-echo "configure:4180: checking if apache is wanted" >&5
+echo "configure:4223: checking if apache is wanted" >&5
  # Check whether --with-apache or --without-apache was given.
 if test "${with_apache+set}" = set; then
   withval="$with_apache"
@@ -4217,7 +4260,7 @@ fi
       # Extract the first word of "httpd", so it can be a program name with args.
 set dummy httpd; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:4221: checking for $ac_word" >&5
+echo "configure:4264: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_APACHE'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -4270,7 +4313,7 @@ fi
     #
     if test -n "1.3.1" ; then
       echo $ac_n "checking apache version >= 1.3.1""... $ac_c" 1>&6
-echo "configure:4274: checking apache version >= 1.3.1" >&5
+echo "configure:4317: checking apache version >= 1.3.1" >&5
       APACHE_REQUEST=`echo 1.3.1 | sed -e 's/\.//g'`
       APACHE_REQUEST_MAJOR=`expr $APACHE_REQUEST : '\(..\)'`
       APACHE_REQUEST_MINOR=`expr $APACHE_REQUEST : '..\(.*\)'`
@@ -4286,7 +4329,7 @@ echo "configure:4274: checking apache version >= 1.3.1" >&5
     #
     HTTP_ROOT=`$APACHE -V | grep HTTPD_ROOT | sed -e 's/.*"\(.*\)"/\1/'`
     echo $ac_n "checking apache modules""... $ac_c" 1>&6
-echo "configure:4290: checking apache modules" >&5
+echo "configure:4333: checking apache modules" >&5
     for dir in libexec modules lib/apache
     do
       if test -f $HTTP_ROOT/$dir/mod_env.*
