Hack  configure  to set OS dependent flags. Only start Apache for tests which actually need it, and kill it afterwards.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1901,6 +1901,72 @@ echo "${ECHO_T}no" >&6
 fi
 
 
+echo "$as_me:$LINENO: checking build system type" >&5
+echo $ECHO_N "checking build system type... $ECHO_C" >&6
+if test "${ac_cv_build+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_build_alias=$build_alias
+test -z "$ac_cv_build_alias" &&
+  ac_cv_build_alias=`$ac_config_guess`
+test -z "$ac_cv_build_alias" &&
+  { { echo "$as_me:$LINENO: error: cannot guess build type; you must specify one" >&5
+echo "$as_me: error: cannot guess build type; you must specify one" >&2;}
+   { (exit 1); exit 1; }; }
+ac_cv_build=`$ac_config_sub $ac_cv_build_alias` ||
+  { { echo "$as_me:$LINENO: error: $ac_config_sub $ac_cv_build_alias failed" >&5
+echo "$as_me: error: $ac_config_sub $ac_cv_build_alias failed" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_build" >&5
+echo "${ECHO_T}$ac_cv_build" >&6
+build=$ac_cv_build
+build_cpu=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
+build_vendor=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
+build_os=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
+
+echo "$as_me:$LINENO: checking host system type" >&5
+echo $ECHO_N "checking host system type... $ECHO_C" >&6
+if test "${ac_cv_host+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_host_alias=$host_alias
+test -z "$ac_cv_host_alias" &&
+  ac_cv_host_alias=$ac_cv_build_alias
+ac_cv_host=`$ac_config_sub $ac_cv_host_alias` ||
+  { { echo "$as_me:$LINENO: error: $ac_config_sub $ac_cv_host_alias failed" >&5
+echo "$as_me: error: $ac_config_sub $ac_cv_host_alias failed" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_host" >&5
+echo "${ECHO_T}$ac_cv_host" >&6
+host=$ac_cv_host
+host_cpu=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
+host_vendor=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
+host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
+
+
+
+
+# Hack to enforce options required by specific systems
+case $host_os in
+   darwin* | rhapsody*)
+     enable_shared=no ; enable_static=yes
+     ac_configure_args="$ac_configure_args --disable-shared --enable-static" ;;
+# (This is only needed for Sun's cc -- do this after CC is set)
+#  solaris* | sunos*)
+#    if test "$CC" != gcc ; then
+#	enable_bigfile=no
+#	ac_configure_args="$ac_configure_args --disable-bigfile"
+#    fi ;;
+esac
+
+
+
+
+
 # Check whether --enable-shared or --disable-shared was given.
 if test "${enable_shared+set}" = set; then
   enableval="$enable_shared"
@@ -1973,52 +2039,6 @@ $ac_config_sub sun4 >/dev/null 2>&1 ||
 echo "$as_me: error: cannot run $ac_config_sub" >&2;}
    { (exit 1); exit 1; }; }
 
-echo "$as_me:$LINENO: checking build system type" >&5
-echo $ECHO_N "checking build system type... $ECHO_C" >&6
-if test "${ac_cv_build+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_build_alias=$build_alias
-test -z "$ac_cv_build_alias" &&
-  ac_cv_build_alias=`$ac_config_guess`
-test -z "$ac_cv_build_alias" &&
-  { { echo "$as_me:$LINENO: error: cannot guess build type; you must specify one" >&5
-echo "$as_me: error: cannot guess build type; you must specify one" >&2;}
-   { (exit 1); exit 1; }; }
-ac_cv_build=`$ac_config_sub $ac_cv_build_alias` ||
-  { { echo "$as_me:$LINENO: error: $ac_config_sub $ac_cv_build_alias failed" >&5
-echo "$as_me: error: $ac_config_sub $ac_cv_build_alias failed" >&2;}
-   { (exit 1); exit 1; }; }
-
-fi
-echo "$as_me:$LINENO: result: $ac_cv_build" >&5
-echo "${ECHO_T}$ac_cv_build" >&6
-build=$ac_cv_build
-build_cpu=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
-build_vendor=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
-build_os=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
-
-
-echo "$as_me:$LINENO: checking host system type" >&5
-echo $ECHO_N "checking host system type... $ECHO_C" >&6
-if test "${ac_cv_host+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_host_alias=$host_alias
-test -z "$ac_cv_host_alias" &&
-  ac_cv_host_alias=$ac_cv_build_alias
-ac_cv_host=`$ac_config_sub $ac_cv_host_alias` ||
-  { { echo "$as_me:$LINENO: error: $ac_config_sub $ac_cv_host_alias failed" >&5
-echo "$as_me: error: $ac_config_sub $ac_cv_host_alias failed" >&2;}
-   { (exit 1); exit 1; }; }
-
-fi
-echo "$as_me:$LINENO: result: $ac_cv_host" >&5
-echo "${ECHO_T}$ac_cv_host" >&6
-host=$ac_cv_host
-host_cpu=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
-host_vendor=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
-host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 
 
 rm -f .deps 2>/dev/null
@@ -14146,6 +14166,28 @@ rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext 
 fi
  CFLAGS=$OLD_CFLAGS
 fi
+
+
+
+
+
+# Hack to enforce options required by specific systems
+case $host_os in
+#  darwin* | rhapsody*)
+#    enable_shared=no ; enable_static=yes
+#    ac_configure_args="$ac_configure_args --disable-shared --enable-static" ;;
+# (This is only needed for Sun's cc -- do this after CC is set)
+   solaris* | sunos*)
+     if test "$CC" != gcc ; then
+	enable_bigfile=no
+	ac_configure_args="$ac_configure_args --disable-bigfile"
+     fi ;;
+esac
+
+
+
+
+
 
 echo "$as_me:$LINENO: checking if --enable-bigfile option specified" >&5
 echo $ECHO_N "checking if --enable-bigfile option specified... $ECHO_C" >&6
diff --git a/test/test_functions.in b/test/test_functions.in
--- a/test/test_functions.in
+++ b/test/test_functions.in
@@ -1,3 +1,8 @@
+# 
+# Initialise variables and directories to prepare to run test suite.
+# If run with argument  --start-apache  it will also start  httpd.
+# If run with argument  --stop-apache   it will stop  httpd  and exit.
+# If there is a problem before the test, "exit 77" skips the test (not fails it)
 #
 # Part of the ht://Dig package   <http://www.htdig.org/>
 # Copyright (c) 1999, 2000 The ht://Dig Group
@@ -5,8 +10,17 @@
 # or the GNU General Public License version 2 or later
 # <http://www.gnu.org/copyleft/gpl.html>
 #
-# $Id: test_functions.in,v 1.8 2002/02/01 22:49:37 ghutchis Exp $
+# $Id: test_functions.in,v 1.9 2003/06/08 07:27:12 lha Exp $
 #
+
+if [ "$1" == --stop-apache ]
+then
+    if [ -n "$httpd"  -a  -f logs/httpd.pid ]
+    then
+	kill -15 `cat logs/httpd.pid`
+	sleep 2
+    fi
+else
 
 testdir=`pwd`
 
@@ -14,7 +28,7 @@ perl=@PERL@
 
 @SET_MAKE@
 
-if test -z "$MAKE"
+if [ -z "$MAKE" ]
 then
 	echo "no make command found"
 	exit 77
@@ -30,35 +44,42 @@ fi
 
 httpd=@APACHE@
 
-if test -z "$httpd"
+# if apache requested, either start it or warn it was not configured.
+if [ "$1" == --start-apache ]
 then
-	echo "no apache server provided. Run configure with --with-apache=<httpd path>"
-	exit 77
-fi
 
-if [ ! -d logs ] 
-then 
-  mkdir -p logs
-else
-  if [ -f logs/httpd.pid ]
-  then
-    kill -15 `cat logs/httpd.pid`
-    sleep 2
-  fi
+    if [ -z "$httpd" ]
+    then
+	    prog_name=`basename $0`
+	    echo "Run configure with --with-apache=<httpd path> to run $prog_name."
+	    exit 77
+    fi
+
+    if [ ! -d logs ] 
+    then 
+      mkdir -p logs
+    else
+      if [ -f logs/httpd.pid ]
+      then
+	kill -15 `cat logs/httpd.pid`
+	sleep 2
+      fi
+    fi
+    if ! $httpd -f $testdir/conf/httpd.conf
+    then
+        echo
+        echo "****Could not start apache. This test may fail, but that is not ht://Dig's fault"
+        echo
+    fi
 fi
-$httpd -f $testdir/conf/httpd.conf
 
 #
 # Prepare htdig test environment
 #
 rm -fr var/htdig
+rm -fr var/htdig2
 mkdir -p var/htdig
 mkdir -p var/htdig2
-
-fail() {
-   echo $1
-   exit 1
-}
 
 htdig=../htdig/htdig
 htsearch=../htsearch/htsearch
@@ -75,8 +96,17 @@ export MIFLUZ_CONFIG ; MIFLUZ_CONFIG=${srcdir}/mifluz.conf
 
 rm -f test test_weakcmpr __db*
 
+#
+# Provide a unified means for scripts to clean up.
+#
 fail() {
-   echo $1
-   exit 1
+    echo "$1"
+    if [ -n "$httpd"  -a  -f logs/httpd.pid ]
+    then
+      kill -15 `cat logs/httpd.pid`
+      sleep 2
+    fi
+    exit 1
 }
 
+fi	# $1 != --stop-apache
