Renamed  regex.h  to  gregex.h  and allow use of  rx  instead.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -881,6 +881,7 @@ Optional Packages:
   --with-search-dir=DIR   where the sample search form should be installed default=$ac_default_prefix/htdocs/htdig
   --with-image-url-prefix=LOCATION   the URL path to the installed images default=/htdig
   --with-search-form=FILE   the name for the sample search form default=search.html
+  --with-rx  with system rx instead of regex default=no
   --with-ssl enable ssl will check /usr/local/ssl
                             /usr/lib/ssl /usr/ssl /usr/pkg /usr/local /usr
 
@@ -2794,7 +2795,7 @@ test x"$silent" = xyes && libtool_flags="$libtool_flags --silent"
 case "$host" in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 2797 "configure"' > conftest.$ac_ext
+  echo '#line 2798 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -3078,6 +3079,15 @@ else
   SEARCH_FORM='search.html'
 fi;
 
+
+
+# Check whether --with-rx or --without-rx was given.
+if test "${with_rx+set}" = set; then
+  withval="$with_rx"
+  WITH_RX="$withval"
+else
+  WITH_RX='no'
+fi;
 
 # Check whether --enable-tests or --disable-tests was given.
 if test "${enable_tests+set}" = set; then
@@ -8886,9 +8896,125 @@ fi
 done
 
 
-echo "$as_me:$LINENO: checking if we should use the included regex?" >&5
+if test $WITH_RX = yes; then
+ if test "${ac_cv_header_rxposix_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for rxposix.h" >&5
+echo $ECHO_N "checking for rxposix.h... $ECHO_C" >&6
+if test "${ac_cv_header_rxposix_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_rxposix_h" >&5
+echo "${ECHO_T}$ac_cv_header_rxposix_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking rxposix.h usability" >&5
+echo $ECHO_N "checking rxposix.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <rxposix.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking rxposix.h presence" >&5
+echo $ECHO_N "checking rxposix.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <rxposix.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: rxposix.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: rxposix.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: rxposix.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: rxposix.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: rxposix.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: rxposix.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: rxposix.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: rxposix.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: rxposix.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: rxposix.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for rxposix.h" >&5
+echo $ECHO_N "checking for rxposix.h... $ECHO_C" >&6
+if test "${ac_cv_header_rxposix_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_rxposix_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_rxposix_h" >&5
+echo "${ECHO_T}$ac_cv_header_rxposix_h" >&6
+
+fi
+if test $ac_cv_header_rxposix_h = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define USE_RX 1
+_ACEOF
+
+else
+  WITH_RX='no'
+fi
+
+
+fi
+if test $WITH_RX = no; then
+ echo "$as_me:$LINENO: checking if we should use the included regex?" >&5
 echo $ECHO_N "checking if we should use the included regex?... $ECHO_C" >&6
-if test "$cross_compiling" = yes; then
+ OLD_CFLAGS=$CFLAGS
+ CFLAGS="$CFLAGS -I${srcdir}/htlib"
+ if test "$cross_compiling" = yes; then
   echo "$as_me:$LINENO: result: unknown" >&5
 echo "${ECHO_T}unknown" >&6;cat >>confdefs.h <<\_ACEOF
 #define HAVE_BROKEN_REGEX 1
@@ -8932,7 +9058,8 @@ _ACEOF
 fi
 rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
-
+ CFLAGS=$OLD_CFLAGS
+fi
 LTLIBOBJS=`echo "$LIBOBJS" | sed 's/\.o/.lo/g'`
 
 
