New configure script dealing with extraction of the berkeley db archive

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1116,12 +1116,44 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
+# Extract the first word of "gunzip", so it can be a program name with args.
+set dummy gunzip; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:1123: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_GUNZIP'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$GUNZIP" in
+  /*)
+  ac_cv_path_GUNZIP="$GUNZIP" # Let the user override the test with a path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
+  for ac_dir in $PATH; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_GUNZIP="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_GUNZIP" && ac_cv_path_GUNZIP="/bin/gunzip"
+  ;;
+esac
+fi
+GUNZIP="$ac_cv_path_GUNZIP"
+if test -n "$GUNZIP"; then
+  echo "$ac_t""$GUNZIP" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
 for ac_prog in tar gnutar
 do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1125: checking for $ac_word" >&5
+echo "configure:1157: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_TAR'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1152,7 +1184,7 @@ test -n "$TAR" || TAR="tar"
 
 
 echo $ac_n "checking for socket in -lsocket""... $ac_c" 1>&6
-echo "configure:1156: checking for socket in -lsocket" >&5
+echo "configure:1188: checking for socket in -lsocket" >&5
 ac_lib_var=`echo socket'_'socket | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1160,7 +1192,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lsocket  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1164 "configure"
+#line 1196 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 #ifdef __cplusplus
@@ -1174,7 +1206,7 @@ int main() {
 socket()
 ; return 0; }
 EOF
-if { (eval echo configure:1178: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:1210: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -1195,7 +1227,7 @@ else
 fi
 
 echo $ac_n "checking for t_accept in -lnsl""... $ac_c" 1>&6
-echo "configure:1199: checking for t_accept in -lnsl" >&5
+echo "configure:1231: checking for t_accept in -lnsl" >&5
 ac_lib_var=`echo nsl'_'t_accept | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1203,7 +1235,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lnsl  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1207 "configure"
+#line 1239 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 #ifdef __cplusplus
@@ -1217,7 +1249,7 @@ int main() {
 t_accept()
 ; return 0; }
 EOF
-if { (eval echo configure:1221: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:1253: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -1242,17 +1274,17 @@ for ac_hdr in sys/time.h fcntl.h limits.h sys/file.h sys/ioctl.h unistd.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:1246: checking for $ac_hdr" >&5
+echo "configure:1278: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1251 "configure"
+#line 1283 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1256: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1288: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -1279,12 +1311,12 @@ fi
 done
 
 echo $ac_n "checking whether time.h and sys/time.h may both be included""... $ac_c" 1>&6
-echo "configure:1283: checking whether time.h and sys/time.h may both be included" >&5
+echo "configure:1315: checking whether time.h and sys/time.h may both be included" >&5
 if eval "test \"`echo '$''{'ac_cv_header_time'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1288 "configure"
+#line 1320 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <sys/time.h>
@@ -1293,7 +1325,7 @@ int main() {
 struct tm *tp;
 ; return 0; }
 EOF
-if { (eval echo configure:1297: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1329: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_header_time=yes
 else
@@ -1315,12 +1347,12 @@ fi
 
 
 echo $ac_n "checking whether struct tm is in sys/time.h or time.h""... $ac_c" 1>&6
-echo "configure:1319: checking whether struct tm is in sys/time.h or time.h" >&5
+echo "configure:1351: checking whether struct tm is in sys/time.h or time.h" >&5
 if eval "test \"`echo '$''{'ac_cv_struct_tm'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1324 "configure"
+#line 1356 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <time.h>
@@ -1328,7 +1360,7 @@ int main() {
 struct tm *tp; tp->tm_sec;
 ; return 0; }
 EOF
-if { (eval echo configure:1332: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1364: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_struct_tm=time.h
 else
@@ -1350,12 +1382,12 @@ fi
 
 
 echo $ac_n "checking for timegm""... $ac_c" 1>&6
-echo "configure:1354: checking for timegm" >&5
+echo "configure:1386: checking for timegm" >&5
 if eval "test \"`echo '$''{'ac_cv_func_timegm'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1359 "configure"
+#line 1391 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char timegm(); below.  */
@@ -1381,7 +1413,7 @@ timegm();
 
 ; return 0; }
 EOF
-if { (eval echo configure:1385: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:1417: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_func_timegm=yes"
 else
@@ -1402,12 +1434,12 @@ EOF
 else
   echo "$ac_t""no" 1>&6
 echo $ac_n "checking if our timegm replacement works""... $ac_c" 1>&6
-echo "configure:1406: checking if our timegm replacement works" >&5;
+echo "configure:1438: checking if our timegm replacement works" >&5;
   if test "$cross_compiling" = yes; then
   echo "$ac_t""I hope so" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1411 "configure"
+#line 1443 "configure"
 #include "confdefs.h"
 #ifdef __cplusplus
 extern "C" void exit(int);
@@ -1417,7 +1449,7 @@ extern "C" void exit(int);
 #include "$srcdir/htlib/timegm.cc"
 
 EOF
-if { (eval echo configure:1421: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1453: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
 then
   echo "$ac_t""yes" 1>&6
 else
@@ -1435,16 +1467,13 @@ fi
 HTDIG_TOP=`pwd`
 
 
-DB_DIR=`echo db-*/build.unix`
-
-
 RX_DIR=`echo rx*`
 
 
 echo $ac_n "checking need gethostname() prototype?""... $ac_c" 1>&6
-echo "configure:1446: checking need gethostname() prototype?" >&5
+echo "configure:1475: checking need gethostname() prototype?" >&5
 cat > conftest.$ac_ext <<EOF
-#line 1448 "configure"
+#line 1477 "configure"
 #include "confdefs.h"
 #include <unistd.h>
 #include <stdio.h>
@@ -1462,7 +1491,7 @@ int main() {
 gethostname("sdsu.edu", (int) 8);
 ; return 0; }
 EOF
-if { (eval echo configure:1466: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1495: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   echo "$ac_t""no" 1>&6
 else
@@ -1478,6 +1507,19 @@ rm -f conftest*
 
 echo ""
 echo "Configuring Berkeley DBM"
+DB_DIR=`echo db-*/build.unix`
+if test ! -d $DB_DIR; then
+  echo "Extracting files..."
+  tarfile=`echo db-*.tar.gz`
+  $GUNZIP < $tarfile | $TAR xf -
+fi
+
+DB_DIR=`echo db-*/build.unix`
+if test ! -d $DB_DIR; then
+  { echo "configure: error: Please extract the Berkeley DB library" 1>&2; exit 1; }
+fi
+
+
 (cd db-*/build.unix; ../dist/configure)
 echo "Berkeley DBM Configuration complete"
 echo ""
@@ -1485,7 +1527,7 @@ echo ""
 # Extract the first word of "tsort", so it can be a program name with args.
 set dummy tsort; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1489: checking for $ac_word" >&5
+echo "configure:1531: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_TSORT'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1663,10 +1705,11 @@ s%@SHELL@%$SHELL%g
 s%@SED@%$SED%g
 s%@SORT@%$SORT%g
 s%@FIND@%$FIND%g
+s%@GUNZIP@%$GUNZIP%g
 s%@TAR@%$TAR%g
 s%@HTDIG_TOP@%$HTDIG_TOP%g
-s%@DB_DIR@%$DB_DIR%g
 s%@RX_DIR@%$RX_DIR%g
+s%@DB_DIR@%$DB_DIR%g
 s%@TSORT@%$TSORT%g
 
 CEOF
